[versions]
kotlin = "1.9.22"
agp = "8.2.2"
compose-compiler = "1.5.8"
hilt = "2.48"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

